[profile.default]
    auto_detect_solc = false
    bytecode_hash = "none"
    cbor_metadata = false
    emv_version = "paris"
    fs_permissions = [{ access = "read", path = "out-optimized" }]
    libs = ["lib"]
    optimizer = true
    optimizer_runs = 200
    out = "out"
    script = "script"
    solc = "0.8.20"
    src = "src"
    test = "test"

[profile.ci.fuzz]
    max_test_rejects = 1_000_000 # Number of times `vm.assume` can fail
    runs = 10_000

[profile.default.invariant]
    call_override = false # Override unsafe external calls to perform reentrancy checks
    depth = 20            # Number of calls executed in one run
    fail_on_revert = true
    runs = 20

[etherscan]
    arbitrum_one = { key = "${API_KEY_ARBISCAN}" }
    avalanche = { key = "${API_KEY_SNOWTRACE" }
    bnb_smart_chain = { key = "${API_KEY_BSCSCAN}" }
    gnosis_chain = { key = "${API_KEY_GNOSISSCAN}" }
    goerli = { key = "${API_KEY_ETHERSCAN}" }
    mainnet = { key = "${API_KEY_ETHERSCAN}" }
    optimism = { key = "${API_KEY_OPTIMISTIC_ETHERSCAN}" }
    polygon = { key = "${API_KEY_POLYGONSCAN}" }
    sepolia = { key = "${API_KEY_ETHERSCAN}" }

[rpc_endpoints]
    arbitrum_one = "https://arbitrum-mainnet.infura.io/v3/${API_KEY_INFURA}"
    avalanche = "https://avalanche-mainnet.infura.io/v3/${API_KEY_INFURA}"
    bnb_smart_chain = "https://bsc-dataseed.binance.org"
    gnosis_chain = "https://rpc.gnosischain.com"
    goerli = "https://goerli.infura.io/v3/${API_KEY_INFURA}"
    localhost = "http://localhost:8545"
    mainnet = "${RPC_URL_MAINNET}"
    optimism = "https://optimism-mainnet.infura.io/v3/${API_KEY_INFURA}"
    polygon = "https://polygon-mainnet.infura.io/v3/${API_KEY_INFURA}"
    sepolia = "https://sepolia.infura.io/v3/${API_KEY_INFURA}"
    mumbai = "https://polygon-mumbai.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
    amoy = "https://polygon-amoy.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
    base-sepolia = "https://base-sepolia.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
