name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install deps
        run: forge install

      - name: Install the Node.js dependencies
        run: yarn install

      - name: Lint the contracts
        run: yarn lint

#      - name: Check gas snapshots
#        run: forge snapshot --check

      - name: Run tests
        run: forge test
